# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cuda_error.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cuda_error.proto',
  package='paddle.platform.proto',
  syntax='proto2',
  serialized_pb=_b('\n\x10\x63uda_error.proto\x12\x15paddle.platform.proto\"6\n\x0bMessageDesc\x12\x11\n\terrorCode\x18\x01 \x02(\x05\x12\x14\n\x0c\x65rrorMessage\x18\x02 \x02(\t\"W\n\x0e\x41llMessageDesc\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x34\n\x08Messages\x18\x02 \x03(\x0b\x32\".paddle.platform.proto.MessageDesc\"K\n\rcudaerrorDesc\x12:\n\x0b\x41llMessages\x18\x02 \x03(\x0b\x32%.paddle.platform.proto.AllMessageDesc')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MESSAGEDESC = _descriptor.Descriptor(
  name='MessageDesc',
  full_name='paddle.platform.proto.MessageDesc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='paddle.platform.proto.MessageDesc.errorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errorMessage', full_name='paddle.platform.proto.MessageDesc.errorMessage', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=97,
)


_ALLMESSAGEDESC = _descriptor.Descriptor(
  name='AllMessageDesc',
  full_name='paddle.platform.proto.AllMessageDesc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='paddle.platform.proto.AllMessageDesc.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Messages', full_name='paddle.platform.proto.AllMessageDesc.Messages', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=186,
)


_CUDAERRORDESC = _descriptor.Descriptor(
  name='cudaerrorDesc',
  full_name='paddle.platform.proto.cudaerrorDesc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AllMessages', full_name='paddle.platform.proto.cudaerrorDesc.AllMessages', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=263,
)

_ALLMESSAGEDESC.fields_by_name['Messages'].message_type = _MESSAGEDESC
_CUDAERRORDESC.fields_by_name['AllMessages'].message_type = _ALLMESSAGEDESC
DESCRIPTOR.message_types_by_name['MessageDesc'] = _MESSAGEDESC
DESCRIPTOR.message_types_by_name['AllMessageDesc'] = _ALLMESSAGEDESC
DESCRIPTOR.message_types_by_name['cudaerrorDesc'] = _CUDAERRORDESC

MessageDesc = _reflection.GeneratedProtocolMessageType('MessageDesc', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEDESC,
  __module__ = 'cuda_error_pb2'
  # @@protoc_insertion_point(class_scope:paddle.platform.proto.MessageDesc)
  ))
_sym_db.RegisterMessage(MessageDesc)

AllMessageDesc = _reflection.GeneratedProtocolMessageType('AllMessageDesc', (_message.Message,), dict(
  DESCRIPTOR = _ALLMESSAGEDESC,
  __module__ = 'cuda_error_pb2'
  # @@protoc_insertion_point(class_scope:paddle.platform.proto.AllMessageDesc)
  ))
_sym_db.RegisterMessage(AllMessageDesc)

cudaerrorDesc = _reflection.GeneratedProtocolMessageType('cudaerrorDesc', (_message.Message,), dict(
  DESCRIPTOR = _CUDAERRORDESC,
  __module__ = 'cuda_error_pb2'
  # @@protoc_insertion_point(class_scope:paddle.platform.proto.cudaerrorDesc)
  ))
_sym_db.RegisterMessage(cudaerrorDesc)


# @@protoc_insertion_point(module_scope)
